<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>EZoptimizer</AssemblyName>
    <Version>0.1.0</Version>
    <Description>Understand your PC. Tune it for what you do.</Description>
  </PropertyGroup>
</Project>
